language: python
python:
  - "3.5"
  - "3.6"      # current detault Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coveralls
# command to run tests
script:
  - python -m nose predicode
